"""Remove all foreign constraint

Revision ID: 0df7a0fc8c18
Revises: 75af96d81b80
Create Date: 2024-09-26 17:27:09.798821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df7a0fc8c18'
down_revision: Union[str, None] = '75af96d81b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_engagement_video_id_fkey', 'user_engagement', type_='foreignkey')
    op.drop_constraint('user_interaction_user_id_fkey', 'user_interaction', type_='foreignkey')
    op.drop_constraint('user_interaction_video_id_fkey', 'user_interaction', type_='foreignkey')
    op.drop_constraint('user_onehot_features_user_id_fkey', 'user_onehot_features', type_='foreignkey')
    op.drop_constraint('video_author_id_fkey', 'video', type_='foreignkey')
    op.drop_constraint('video_caption_video_id_fkey', 'video_caption', type_='foreignkey')
    op.drop_constraint('video_interaction_video_id_fkey', 'video_interaction', type_='foreignkey')
    op.drop_constraint('video_statistic_video_id_fkey', 'video_statistic', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('video_statistic_video_id_fkey', 'video_statistic', 'video', ['video_id'], ['video_id'])
    op.create_foreign_key('video_interaction_video_id_fkey', 'video_interaction', 'video', ['video_id'], ['video_id'])
    op.create_foreign_key('video_caption_video_id_fkey', 'video_caption', 'video', ['video_id'], ['video_id'])
    op.create_foreign_key('video_author_id_fkey', 'video', 'user', ['author_id'], ['user_id'])
    op.create_foreign_key('user_onehot_features_user_id_fkey', 'user_onehot_features', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('user_interaction_video_id_fkey', 'user_interaction', 'video', ['video_id'], ['video_id'])
    op.create_foreign_key('user_interaction_user_id_fkey', 'user_interaction', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('user_engagement_video_id_fkey', 'user_engagement', 'video', ['video_id'], ['video_id'])
    # ### end Alembic commands ###
