"""Initialize database

Revision ID: 63f410d19131
Revises: 
Create Date: 2024-09-26 16:12:42.445492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f410d19131'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_active_degree', sa.String(), nullable=True),
    sa.Column('is_lowactive_period', sa.Integer(), nullable=True),
    sa.Column('is_live_streamer', sa.Integer(), nullable=True),
    sa.Column('is_video_author', sa.Integer(), nullable=True),
    sa.Column('follow_user_num', sa.Integer(), nullable=True),
    sa.Column('follow_user_num_range', sa.String(), nullable=True),
    sa.Column('fans_user_num', sa.Integer(), nullable=True),
    sa.Column('fans_user_num_range', sa.String(), nullable=True),
    sa.Column('friend_user_num', sa.Integer(), nullable=True),
    sa.Column('friend_user_num_range', sa.String(), nullable=True),
    sa.Column('register_days', sa.Integer(), nullable=True),
    sa.Column('register_days_range', sa.String(), nullable=True),
    sa.CheckConstraint("user_active_degree in ('full_active',                           'high_active', 'middle_active', 'UNKNOWN')"),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_onehot_features',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('onehot_feat0', sa.Float(), nullable=True),
    sa.Column('onehot_feat1', sa.Float(), nullable=True),
    sa.Column('onehot_feat2', sa.Float(), nullable=True),
    sa.Column('onehot_feat3', sa.Float(), nullable=True),
    sa.Column('onehot_feat4', sa.Float(), nullable=True),
    sa.Column('onehot_feat5', sa.Float(), nullable=True),
    sa.Column('onehot_feat6', sa.Float(), nullable=True),
    sa.Column('onehot_feat7', sa.Float(), nullable=True),
    sa.Column('onehot_feat8', sa.Float(), nullable=True),
    sa.Column('onehot_feat9', sa.Float(), nullable=True),
    sa.Column('onehot_feat10', sa.Float(), nullable=True),
    sa.Column('onehot_feat11', sa.Float(), nullable=True),
    sa.Column('onehot_feat12', sa.Float(), nullable=True),
    sa.Column('onehot_feat13', sa.Float(), nullable=True),
    sa.Column('onehot_feat14', sa.Float(), nullable=True),
    sa.Column('onehot_feat15', sa.Float(), nullable=True),
    sa.Column('onehot_feat16', sa.Float(), nullable=True),
    sa.Column('onehot_feat17', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('video',
    sa.Column('video_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('upload_dt', sa.DateTime(), nullable=False),
    sa.Column('upload_type', sa.String(), nullable=False),
    sa.Column('visible_status', sa.String(), nullable=False),
    sa.Column('video_duration', sa.Float(), nullable=False),
    sa.Column('video_width', sa.Integer(), nullable=False),
    sa.Column('video_height', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('user_engagement',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('report_cnt', sa.Integer(), nullable=True),
    sa.Column('report_user_num', sa.Integer(), nullable=True),
    sa.Column('reduce_similar_cnt', sa.Integer(), nullable=True),
    sa.Column('reduce_similar_user_num', sa.Integer(), nullable=True),
    sa.Column('collect_cnt', sa.Integer(), nullable=True),
    sa.Column('collect_user_num', sa.Integer(), nullable=True),
    sa.Column('cancel_collect_cnt', sa.Integer(), nullable=True),
    sa.Column('cancel_collect_user_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], ),
    sa.PrimaryKeyConstraint('video_id', 'date')
    )
    op.create_table('video_caption',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('manual_cover_text', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('topic_tag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('video_interaction',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('like_cnt', sa.Integer(), nullable=True),
    sa.Column('like_user_num', sa.Integer(), nullable=True),
    sa.Column('click_like_cnt', sa.Integer(), nullable=True),
    sa.Column('double_click_cnt', sa.Integer(), nullable=True),
    sa.Column('cancel_like_cnt', sa.Integer(), nullable=True),
    sa.Column('cancel_like_user_num', sa.Integer(), nullable=True),
    sa.Column('comment_cnt', sa.Integer(), nullable=True),
    sa.Column('comment_user_num', sa.Integer(), nullable=True),
    sa.Column('direct_comment_cnt', sa.Integer(), nullable=True),
    sa.Column('reply_comment_cnt', sa.Integer(), nullable=True),
    sa.Column('delete_comment_cnt', sa.Integer(), nullable=True),
    sa.Column('delete_comment_user_num', sa.Integer(), nullable=True),
    sa.Column('comment_like_cnt', sa.Integer(), nullable=True),
    sa.Column('comment_like_user_num', sa.Integer(), nullable=True),
    sa.Column('follow_cnt', sa.Integer(), nullable=True),
    sa.Column('follow_user_num', sa.Integer(), nullable=True),
    sa.Column('cancel_follow_cnt', sa.Integer(), nullable=True),
    sa.Column('cancel_follow_user_num', sa.Integer(), nullable=True),
    sa.Column('share_cnt', sa.Integer(), nullable=True),
    sa.Column('share_user_num', sa.Integer(), nullable=True),
    sa.Column('download_cnt', sa.Integer(), nullable=True),
    sa.Column('download_user_num', sa.Integer(), nullable=True),
    sa.Column('report_cnt', sa.Integer(), nullable=True),
    sa.Column('report_user_num', sa.Integer(), nullable=True),
    sa.Column('reduce_similar_cnt', sa.Integer(), nullable=True),
    sa.Column('reduce_similar_user_num', sa.Integer(), nullable=True),
    sa.Column('collect_cnt', sa.Integer(), nullable=True),
    sa.Column('collect_user_num', sa.Integer(), nullable=True),
    sa.Column('cancel_collect_cnt', sa.Integer(), nullable=True),
    sa.Column('cancel_collect_user_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], ),
    sa.PrimaryKeyConstraint('video_id', 'date')
    )
    op.create_table('video_statistic',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('show_cnt', sa.Integer(), nullable=True),
    sa.Column('show_user_num', sa.Integer(), nullable=True),
    sa.Column('play_cnt', sa.Integer(), nullable=True),
    sa.Column('play_user_num', sa.Integer(), nullable=True),
    sa.Column('play_duration', sa.Integer(), nullable=True),
    sa.Column('complete_play_cnt', sa.Integer(), nullable=True),
    sa.Column('complete_play_user_num', sa.Integer(), nullable=True),
    sa.Column('valid_play_cnt', sa.Integer(), nullable=True),
    sa.Column('valid_play_user_num', sa.Integer(), nullable=True),
    sa.Column('long_time_play_cnt', sa.Integer(), nullable=True),
    sa.Column('long_time_play_user_num', sa.Integer(), nullable=True),
    sa.Column('short_time_play_cnt', sa.Integer(), nullable=True),
    sa.Column('short_time_play_user_num', sa.Integer(), nullable=True),
    sa.Column('play_progress', sa.Float(), nullable=True),
    sa.Column('comment_stay_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], ),
    sa.PrimaryKeyConstraint('video_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_statistic')
    op.drop_table('video_interaction')
    op.drop_table('video_caption')
    op.drop_table('user_engagement')
    op.drop_table('video')
    op.drop_table('user_onehot_features')
    op.drop_table('user')
    # ### end Alembic commands ###
