name: "0_transformworkflowtriton"
input {
  name: "user_id"
  data_type: TYPE_INT64
  dims: -1
}
input {
  name: "onehot_feat0"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat1"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat2"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat3"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat5"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat6"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat7"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat8"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat9"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat10"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat11"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat4"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat12"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat13"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat14"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat15"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat16"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "onehot_feat17"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "is_lowactive_period"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "is_live_streamer"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "is_video_author"
  data_type: TYPE_FP64
  dims: -1
}
input {
  name: "follow_user_num_range"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "fans_user_num_range"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "friend_user_num_range"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "register_days_range"
  data_type: TYPE_STRING
  dims: -1
}
output {
  name: "user_id"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat0"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat1"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat2"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat3"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat5"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat6"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat7"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat8"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat9"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat10"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat11"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat4"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat12"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat13"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat14"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat15"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat16"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "onehot_feat17"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "is_lowactive_period"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "is_live_streamer"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "is_video_author"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "follow_user_num_range"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "fans_user_num_range"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "friend_user_num_range"
  data_type: TYPE_INT32
  dims: -1
}
output {
  name: "register_days_range"
  data_type: TYPE_INT32
  dims: -1
}
instance_group {
}
parameters {
  key: "cats"
  value {
  }
}
parameters {
  key: "conts"
  value {
  }
}
parameters {
  key: "python_module"
  value {
    string_value: "merlin.systems.triton.models.workflow_model"
  }
}
backend: "python"
